NDefines.NTechnology.DONT_EXECUTE_TECH_BEFORE = 2527
NDefines.NTechnology.IDEAL_YEAR_LEVEL_0 = 2500
NDefines.NTechnology.IDEAL_YEAR_LEVEL_8 = 3300

NDefines.NEngine.MISSING_SCRIPTED_SUCCESSOR_ERROR_CUTOFF_YEAR = 2530